PWD = $(shell /bin/pwd)
RESULT = ex03
SOURCES = 	atom.ml \
			lst_atoms.ml \
			molecule.ml \
			lst_molecules.ml \
			alkane.ml \
			lst_alkanes.ml \
			reaction.ml \
			main.ml
LIBS =
OCAMLMAKEFILE = $(PWD)/../OCamlMakefile
include $(OCAMLMAKEFILE)
