PWD = $(shell /bin/pwd)
RESULT = ex00
SOURCES = 	atom.ml \
			hydrogen.ml \
			carbon.ml \
			oxygen.ml \
			platinum.ml \
			arsenic.ml \
			zinc.ml \
			main.ml
LIBS =
OCAMLMAKEFILE = $(PWD)/../OCamlMakefile
include $(OCAMLMAKEFILE)
